import { execFile } from 'node:child_process';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { promisify } from 'node:util';

import { afterEach, describe, expect, it } from 'vitest';

const execFileAsync = promisify(execFile);
const temporaryDirectories: string[] = [];
const script = resolve('scripts/generate-notices.mjs');

afterEach(async () => {
  const { rm } = await import('node:fs/promises');
  await Promise.all(
    temporaryDirectories.splice(0).map((directory) =>
      rm(directory, {
        recursive: true,
        force: true,
      }),
    ),
  );
});

describe('generate-notices', () => {
  it('generates a sorted notice only for the pinned bundled dependency inventory', async () => {
    const root = await mkdtemp(join(tmpdir(), 'proofline-notices-'));
    temporaryDirectories.push(root);
    await writeFile(
      join(root, 'pnpm-lock.yaml'),
      [
        'lockfileVersion: 9.0',
        'packages:',
        "  '@actions/core@3.0.1': {}",
        '  zod@4.5.4: {}',
        '  unrelated@9.9.9: {}',
        '',
      ].join('\n'),
    );

    for (const dependency of [
      {
        path: '@actions+core@3.0.1/node_modules/@actions/core',
        manifest: {
          name: '@actions/core',
          version: '3.0.1',
          license: 'MIT',
          repository: { url: 'git+https://github.com/actions/toolkit.git' },
        },
      },
      {
        path: 'zod@4.5.4/node_modules/zod',
        manifest: {
          name: 'zod',
          version: '4.5.4',
          license: 'MIT',
          repository: 'git+https://github.com/colinhacks/zod.git',
        },
      },
    ]) {
      const manifestPath = join(
        root,
        'node_modules/.pnpm',
        dependency.path,
        'package.json',
      );
      await mkdir(dirname(manifestPath), { recursive: true });
      await writeFile(manifestPath, `${JSON.stringify(dependency.manifest)}\n`);
      await writeFile(
        join(dirname(manifestPath), 'LICENSE'),
        `License for ${dependency.manifest.name}\nSecond line\n`,
      );
    }

    const inventoryPath = join(root, 'inventory.json');
    await writeFile(
      inventoryPath,
      `${JSON.stringify(['zod@4.5.4', '@actions/core@3.0.1'])}\n`,
    );
    const outputPath = join(root, 'THIRD_PARTY_NOTICES.md');

    await execFileAsync(process.execPath, [
      script,
      '--root',
      root,
      '--inventory',
      inventoryPath,
      '--output',
      outputPath,
    ]);

    await expect(readFile(outputPath, 'utf8')).resolves.toBe(
      [
        '# Third-Party Notices',
        '',
        'Proofline distributes the following third-party packages in its bundled GitHub Action:',
        '',
        '| Package         | Version | License | Source                             |',
        '| --------------- | ------- | ------- | ---------------------------------- |',
        '| `@actions/core` | 3.0.1   | MIT     | https://github.com/actions/toolkit |',
        '| `zod`           | 4.5.4   | MIT     | https://github.com/colinhacks/zod  |',
        '',
        'Generated by `check/scripts/generate-notices.mjs` from the pinned inventory and `pnpm-lock.yaml`.',
        '',
        '## License Texts',
        '',
        '### `@actions/core@3.0.1`',
        '',
        '    License for @actions/core',
        '    Second line',
        '',
        '### `zod@4.5.4`',
        '',
        '    License for zod',
        '    Second line',
        '',
      ].join('\n'),
    );
  });

  it('fails instead of publishing a notice when an inventory version is absent from the lockfile', async () => {
    const root = await mkdtemp(join(tmpdir(), 'proofline-notices-'));
    temporaryDirectories.push(root);
    await writeFile(
      join(root, 'pnpm-lock.yaml'),
      'lockfileVersion: 9.0\npackages: {}\n',
    );
    const inventoryPath = join(root, 'inventory.json');
    await writeFile(inventoryPath, '["zod@4.5.4"]\n');

    try {
      await execFileAsync(process.execPath, [
        script,
        '--root',
        root,
        '--inventory',
        inventoryPath,
        '--output',
        join(root, 'notices.md'),
      ]);
      throw new Error('expected notice generation to fail');
    } catch (error) {
      if (
        !(error instanceof Error) ||
        !('stderr' in error) ||
        typeof error.stderr !== 'string'
      ) {
        throw error;
      }
      expect(error.stderr).toContain(
        'bundled dependency zod@4.5.4 is not pinned in pnpm-lock.yaml',
      );
    }
  });

  it('fails when the pinned inventory omits a resolved production dependency', async () => {
    const root = await mkdtemp(join(tmpdir(), 'proofline-notices-'));
    temporaryDirectories.push(root);
    await writeFile(join(root, 'pnpm-lock.yaml'), 'lockfileVersion: 9.0\n');
    const inventoryPath = join(root, 'inventory.json');
    const resolvedInventoryPath = join(root, 'resolved.json');
    await writeFile(inventoryPath, '["zod@4.5.4"]\n');
    await writeFile(
      resolvedInventoryPath,
      '["zod@4.5.4","unexpected@1.0.0"]\n',
    );

    try {
      await execFileAsync(process.execPath, [
        script,
        '--root',
        root,
        '--inventory',
        inventoryPath,
        '--resolved-inventory',
        resolvedInventoryPath,
        '--output',
        join(root, 'notices.md'),
      ]);
      throw new Error('expected notice generation to fail');
    } catch (error) {
      if (
        !(error instanceof Error) ||
        !('stderr' in error) ||
        typeof error.stderr !== 'string'
      ) {
        throw error;
      }
      expect(error.stderr).toContain(
        'bundled dependency inventory differs from the resolved production dependency closure',
      );
    }
  });
});
